# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

cmu_lti:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /jet/home/jhou/project/11711-End-to-end-NLP-System-Building/chunked_doc.tsv
  id_prefix: 'cmu_lti:'