# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

cmu_lti:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/ec2-user/11711-a2/data/chunked_contexts/chunked_doc.tsv
  id_prefix: 'cmu_lti:'

cmu_lti_papers:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/ec2-user/11711-a2/data/chunked_contexts/chunked_doc_papers.tsv
  id_prefix: 'cmu_lti:'